name: Deploy Streamlit
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Docker
      run: docker build -t myuser/streamlit:latest ./streamlit_ui