FROM apache/airflow:2.6.0

COPY . .

RUN pip install --no-cache-dir -r requirements.txt

# ENTRYPOINT ["jupyter", "lab","--ip=0.0.0.0","--allow-root"]
#CMD ["api:app", "--host", "0.0.0.0", "--port", "8989"]