apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - fastapi-deployment.yaml
  - streamlit-deployment.yaml
  - mlflow-deployment.yaml
  - airflow-deployment.yaml

namespace: mlops

commonLabels:
  project: housing-mlops