apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  namespace: mlops
spec:
  storageClassName: microk8s-hostpath
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 5Gi


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: mlops
spec:
  replicas: 1
  selector: { matchLabels: { app: postgres } }
  template:
    metadata: { labels: { app: postgres } }
    spec:
      containers:
        - name: postgres
          image: postgres:14
          envFrom: [{ secretRef: { name: mlops-secrets } }]
          ports: [{ containerPort: 5432 }]
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: data
          persistentVolumeClaim: { claimName: postgres-data }

---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: mlops
spec:
  selector: { app: postgres }
  type: NodePort
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 30007  # puedes elegir cualquier puerto libre en el rango 30000–32767