apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit
  namespace: mlops
spec:
  replicas: 1
  selector: { matchLabels: { app: streamlit } }
  template:
    metadata: { labels: { app: streamlit } }
    spec:
      containers:
        - name: streamlit
          # image: jeanrod1/streamlit:__VERSION__
          image: jeanrod1/streamlit:latest
          env:
            - { name: API_URL, value: "http://api-service.mlops.svc.cluster.local" }
          ports: [{ containerPort: 8501 }]
---
apiVersion: v1
kind: Service
metadata:
  name: streamlit
  namespace: mlops
spec:
  type: NodePort
  selector:
    app: streamlit
  ports:
    - port: 80
      targetPort: 8501
      nodePort: 30010  # puedes elegir un puerto entre 30000–32767