apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi
  namespace: mlops
spec:
  replicas: 2
  selector: { matchLabels: { app: fastapi } }
  template:
    metadata: { labels: { app: fastapi } }
    spec:
      containers:
        - name: fastapi
          image: jeanrod1/fastapi:latest
          envFrom: 
            - secretRef: { name: mlops-secrets }
          ports: [ { containerPort: 8000 } ]
          resources:
            limits:
              cpu: "2"
              memory: "1000Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: fastapi
  namespace: mlops
spec:
  type: NodePort
  selector:
    app: fastapi
  ports:
    - port: 80
      targetPort: 8000
      nodePort: 30012