apiVersion: apps/v1
kind: Deployment
metadata:
  name: locust
  namespace: mlops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: locust
  template:
    metadata:
      labels:
        app: locust
    spec:
      containers:
        - name: locust
          image: locustio/locust
          command: ["locust", "-f", "/locust/locustfile.py",
                    "--host", "http://fastapi.mlops.svc.cluster.local"]
          ports:
            - containerPort: 8089
          volumeMounts:
            - name: locustfile
              mountPath: /locust
      volumes:
        - name: locustfile
          configMap:
            name: locustfile
---
apiVersion: v1
kind: Service
metadata:
  name: locust
  namespace: mlops
spec:
  type: NodePort
  selector:
    app: locust
  ports:
    - port: 8089
      targetPort: 8089
      nodePort: 30015