apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-data
  namespace: mlops
spec:
  storageClassName: microk8s-hostpath
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 10Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: mlops
spec:
  replicas: 1
  selector: { matchLabels: { app: minio } }
  template:
    metadata: { labels: { app: minio } }
    spec:
      containers:
        - name: minio
          image: minio/minio
          args: [ "server", "/data", "--console-address", ":9001" ]
          envFrom: [{ secretRef: { name: mlops-secrets } }]
          ports:
            - { containerPort: 9000 }
            - { containerPort: 9001 }
          volumeMounts:
            - { name: data, mountPath: /data }
      volumes:
        - { name: data, persistentVolumeClaim: { claimName: minio-data } }

---
apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: mlops
spec:
  type: NodePort
  ports:
    - port: 9000
      targetPort: 9000
      nodePort: 30001
  selector:
    app: minio