apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow
  namespace: mlops
spec:
  replicas: 1
  selector: { matchLabels: { app: mlflow } }
  template:
    metadata: { labels: { app: mlflow } }
    spec:
      containers:
        - name: mlflow
          image: python:3.10-slim
          envFrom: [{ secretRef: { name: mlops-secrets } }]
          command: ["/bin/sh","-c"]
          args:
            - |
              pip install mlflow boto3 psycopg2-binary && \
              mlflow server \
                --backend-store-uri postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@postgres:5432/$(POSTGRES_DB) \
                --default-artifact-root s3://$(S3_BUCKET)/ \
                --host 0.0.0.0 --port 5000
          ports: [{ containerPort: 5000 }]
---
apiVersion: v1
kind: Service
metadata:
  name: mlflow
  namespace: mlops
spec:
  selector: { app: mlflow }
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30008  # puedes elegir cualquier puerto libre en el rango 30000–32767