apiVersion: v1
kind: Secret
metadata:
  name: mlops-secrets
  namespace: mlops 
type: Opaque
data:
  POSTGRES_USER: bWxvcHM=  # 'mlops'
  POSTGRES_PASSWORD: bWxvcHM=  # 'mlops'
  POSTGRES_DB: ZGlhYmV0ZXM=  # 'diabetes'
  POSTGRES_HOST: MTcyLjMwLjE3My4w  # '172.30.173.0'
  POSTGRES_PORT: MzAwMDc=  # '30007'
  RAW_SCHEMA: cmF3  # 'raw'
  CLEAN_SCHEMA: Y2xlYW4=  # 'clean'
  MLFLOW_URI: aHR0cDovLzE3Mi4zMC4xNzMuMDozMDAwOA==  # 'http://172.30.173.0:30008'

  # MLflow + MinIO extras:
  AWS_ACCESS_KEY_ID: bWluaW9hZG1pbg==  # 'minioadmin'
  AWS_SECRET_ACCESS_KEY: bWluaW9hZG1pbg==  # 'minioadmin'
  MLFLOW_S3_ENDPOINT_URL: aHR0cDovLzE3Mi4zMC4xNzMuMDozMDAwMQ==  # 'http://172.30.173.0:30001'
  S3_BUCKET: bWxmcm93  # 'mlflow'
  MINIO_ROOT_USER: bWluaW9hZG1pbg==  # 'minioadmin'
  MINIO_ROOT_PASSWORD: bWluaW9hZG1pbg==  # 'minioadmin'

