apiVersion: v1
kind: Secret
metadata:
  name: mlops-secrets
  namespace: mlops 
type: Opaque
data:
  POSTGRES_USER: bWxvcHM=  # Valor base64 de 'mlops'
  POSTGRES_PASSWORD: bWxvcHM=  # Valor base64 de 'mlops'
  POSTGRES_DB: ZGlhYmV0ZXM=  # Valor base64 de 'diabetes'
  POSTGRES_HOST: MTAuNDMuMTAxLjE5NA==  # Valor base64 de '10.43.101.194'
  POSTGRES_PORT: MzAwMDc=  # Valor base64 de '30007'
  RAW_SCHEMA: cmF3  # Valor base64 de 'raw'
  CLEAN_SCHEMA: Y2xlYW4=  # Valor base64 de 'clean'
  MLFLOW_URI: aHR0cDovL21sZmxvdy1wZXJmOjUwMDA=  # Valor base64 de 'http://mlflow:5000'
  S3_BUCKET: bWxmcm93  # Valor base64 de 'mlflow'
