version: '3'  # Especifica la versión de Docker Compose que se está utilizando.

services:     # Define los servicios que se ejecutarán en contenedores Docker.
  jupyterlab: # Nombre del servicio
    build: .
    # image: python:3.9
    container_name: jupyterlab
    volumes:
      - ./models:/app/models
      - ./notebooks:/app/notebooks  # Volumen compartido para los modelos
    ports:
      - "8888:8888"
    command: >
      sh -c "jupyter lab --ip=0.0.0.0 --port=8888 --allow-root"

  api:
    build: .
    container_name: ml_api
    volumes:
      - ./models:/app/models
      - ./notebooks:/app/notebooks  # Volumen compartido para los modelos
    ports:
      - "8000:8000"
    command: >
      sh -c "uvicorn api:app --host 0.0.0.0 --port 8000 --reload" 

    # Define el comando que se ejecutará al iniciar el contenedor.
    # --host 0.0.0.0: Permite que la aplicación sea accesible desde cualquier IP dentro de la red del contenedor.
    # --port 80: La aplicación se ejecutará en el puerto 80 dentro del contenedor.
    # --reload: Activa el modo de recarga automática, útil para entornos de desarrollo ya que reinicia el servidor si hay cambios en el código.
