apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: jeanrod1/fastapi-api:latest
        imagePullPolicy: Always  # ← obliga a que siempre busque la última imagen
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 80          # El puerto que expone el service (externo en cluster)
      targetPort: 8000  # Puerto interno en el pod (donde escucha tu app)
