apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadtester
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loadtester
  template:
    metadata:
      labels:
        app: loadtester
    spec:
      containers:
      - name: loadtester
        image: jeanrod1/loadtester:latest
        imagePullPolicy: Always  # ← obliga a que siempre busque la última imagen
