version: '3'

services:
  jupyterlab:
    build: .
    container_name: jupyterlab_tfx
    volumes:
      - .:/app
    ports:
      - "8888:8888"
      - "6006:6006"
    stdin_open: true
    tty: true
    restart: unless-stopped
