version: '3'  # Especifica la versión de Docker Compose que se está utilizando.

services:     # Define los servicios que se ejecutarán en contenedores Docker.
  jupyterlab: # Nombre del servicio
    build: .
    # image: python:3.9
    container_name: jupyterlab
    volumes:
      - ./models:/app/models
      - ./notebooks:/app/notebooks  # Volumen compartido para los modelos
    ports:
      - "8888:8888"
    command: >
      sh -c "uv run jupyter lab --ip=0.0.0.0 --port=8888 --allow-root"